### ISSUE TITLE
Still unicode errors

### ISSUE THREAD

**Issue by kjcole** [mjsir911/ConfigMaker#2]
The good news is, it runs. Some wonky font sizing on this Mac, but tolerable (and fixable). However, I attempted to create an experiment with a single trial, and a single rating (5 checkboxes). On saving I see:

```
Traceback (most recent call last):
  File "./makeconf.py", line 182, in export_data
    self.write(savefilepath)
  File "./makeconf.py", line 265, in write
    json.dump(data, outfile, **pretty_print)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 190, in dump
    fp.write(chunk)
TypeError: must be unicode, not str
```
It created an empty JSON file.

**Comment by mjsir911** [comment]
9b76963 should have fixed these issues. Are they still happening?

**Comment by kjcole** [comment]
It seems okay on Linux today. I'll try from the Mac tomorrow.
