### ISSUE TITLE
pathlib with shutil complicates life, rather than simplifying it

### ISSUE THREAD

**Issue by kjcole** [mjsir911/ConfigMaker#28]
I'm fixing this in my fork now, but...
When attempting to overwrite an existing folder, I get your warning message. But if I choose to ignore it, the program bails with:

```
2017-09-18 17:08:48.042 python[2637:132195] modalSession has been exited prematurely - check for a reentrant call to endModalSession:
2017-09-18 17:09:43.703 python[2637:132195] modalSession has been exited prematurely - check for a reentrant call to endModalSession:
/Users/kyma/.config/sound-advice/presets/wacky
INFO:root:path given to save is "/Users/kyma/.config/sound-advice/presets/wacky"
INFO:root:Hello i am write
2017-09-18 17:10:04.737 python[2637:132195] modalSession has been exited prematurely - check for a reentrant call to endModalSession:
Traceback (most recent call last):
  File "/Users/kyma/Code/marco/ConfigMaker/src/shared.py", line 167, in export_data
    self.write(save_as=True)
  File "presets.py", line 94, in write
    super().write(save_as)
  File "/Users/kyma/Code/marco/ConfigMaker/src/shared.py", line 194, in write
    shutil.move(path, oldstuff)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 294, in move
    os.rename(src, real_dst)
TypeError: coercing to Unicode: need string or buffer, PosixPath found
```
For the fix I'm looking at:

https://stackoverflow.com/questions/33625931/copy-file-with-pathlib-in-python

**Comment by mjsir911** [comment]
PR Fixed this
